### PR TITLE
Adding CodeQL - security code scanner

### PR DESCRIPTION
**Pull request by zivnevo**

### CODE REVIEW

**Comment by orozery** [comment]
I see there's also a configuration here:
[github/codeql-action](https://docs.github.com/en/code-security/code-scanning/enabling-code-scanning/configuring-default-setup-for-code-scanning)

How does this relates to your proposed changed?

**Comment by zivnevo** [comment]
> I see there's also a configuration here: [github/codeql-action](https://docs.github.com/en/code-security/code-scanning/enabling-code-scanning/configuring-default-setup-for-code-scanning)
> 
> How does this relates to your proposed changed?

In the end it all ends up with similar Workflow YAML.

**Comment by zivnevo** [comment]
@elevran , ok to merge?

**Review by elevran — APPROVED** [review]
Let's monitor the resources and time associated with this and see what it discovers.

**Pull request merged**
