### PR TITLE
Send attributes of source workload to remote peer

### LINKED ISSUE #293: Sending attributes of the client workload in a connection request
When a workload is trying to connect to a remote service, the local peer must send all workload attributes to the remote peer, so the remote peer can make a decision whether access is permitted or not.

### PR DESCRIPTION
**Pull request by zivnevo**
Fixes #293

### CODE REVIEW

**Comment by elevran** [comment]
where does the collection of attributes done?

**Comment by zivnevo** [comment]
> where does the collection of attributes done?

Currently it is done on the peer at the client-workload side when authorizing the egress request (`Manager::authorizeEgress`).
We may decide to move it to another function/struct when there is enough "beef" around it.
The idea behind this PR is that both peers will use exactly the same set of attributes for the source workload.

**Comment by orozery** [comment]
@elevran Recall your suggestion of switching tunnel-establishment

**Comment by orozery** [comment]
Sorry, closed by mistake. Re-opened.

**Review by elevran — APPROVED** [review]

**Comment by elevran** [comment]
so this just makes sure we send/use the attributes and does not affect which are collect, right?

**Comment by zivnevo** [comment]
> so this just makes sure we send/use the attributes and does not affect which are collect, right?

right

**Pull request merged**
